name: CI Workflow

on:
  push:
    branches:
      - master

jobs:
  all-in-one:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Docker
      run: sudo service docker start

    - name: Run Docker Compose and WP CLI
      run: |
        docker-compose up -d --build
        until docker-compose exec mysql mysql -u root -ppassword -e 'SELECT 1'; do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done
        docker-compose run --rm wp-cli install-wp
        sleep 10
        docker pull wpscanteam/wpscan
        sleep 5
        docker run --network dvwp_default wpscanteam/wpscan wpscan --url http://wordpress/
        docker-compose down
